---
title: "Welfare Analysis"
output: beamer_presentation
theme: "Berlin"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## Goals

+ Develop some measure of how well off people are before and after policy changes -- welfare analysis
+ Show the welfare effects of a price ceilings and floors
+ Use the same tools to show the effects of a tax.

## Big Takeaways Part 1

When you have a *well-functioning* market and you add a price floor...

+ There is a loss to society
+ Buyers lose
+ Sellers that can sell win for sure.
+ Sellers overall may gain or lose depending on a few things.

## Big Takeaways Part 2

When you have a *well-functioning* market and you add a tax...

+ There is a loss to society within this market
+ Price may go up or down depending on, 'who writes the check'
+ Tax revenue is collected but ...
    + Some comes from the buyers and some from the sellers
    + The shares depend on price sensitivity and not 'who writes the check'
    

## Economists Concerns

Different from others.  We tend to get focused on two things:

+ Efficiency:  Did the right people make the right amount of the right stuff the right way and did it go to the right people.  (There are about 5 kinds of efficiency there)
+ Welfare:  How well-off everyone is.


## Welfare

+ Not free money.
+ How well-off we are.
    + Are you better off with 10% more income but with the price of rent being 25% higher?
    + Are you better off with 10% less cheese but 15% more bread?
    
    
## Three Major Measures

+ EC 311 Topics

    + Compensating Variation 
    + Equivelent Variation
+ This class

    + The surplus measures
    + Consumer suplus
    + Producer surplus, profits plus fixed cost
    + Deadweight loss, losses to society
    
## Consumer Surplus

+ "Gross Surplus" 

    + the benefit you get from consuming goods.
    + The area under the demand function up to quantity you consumed.

+ "Consumer Surplus"

    + The benefit you get from consumer goods, net of what you paid for them.
    + The area under the demand function, above price, up to quantity consumed.
    
    
    
## Graphically


## Things to spot

+ When your consumption increases:

    + gross surplus increases

+ When price goes down:

    + you consume more
    + Consumer surplus increases
    
## Producer Surplus    

+ The benefit firms get from selling goods, net of what variable costs.
    + The area above the supply function, below price, up to quantity sold.
    
## Graphically


## Things to spot

+ When price goes down:

    + You sell less
    + Producer surplus decreases

## Put Both CS and PS on the same graph


## Now Try a Price above Equilibrium


## Things to Spot

+ Fewer transactions, remember you need buyers and sellers for transactions
+ There is less total surplus, consumer + producer.
    + The part lost is called deadweight loss.
    + Only the equilibrium price makes that triangle go away.
    
In a well-functioning perfectly competitive market, equilibrium prices maximize social welfare.

## Lets Look at Welfare Changes

+ Impose a price floor.
+ Look at CS before and after
+ Look at PS before and after
+ Look at transfers from one to the other
+ Look at losses to society.

## Graphically


## Things to Spot

+ Consumers lose for sure
+ There is a loss to society
+ Some consumer surplus is transferred to sellers
+ Producers:
    + Get some surplus from consumers
    + Lose some surplus because of lost sales
    + Those that sell, are better off
    + In net, it depends on the size of their loss from lost sales and the transfer from consumers.
  
There will be a price ceiling in the homework.

## Interpretation of DWL


+ The cost of implementing the non-price allocation mechanisms (Price ceiling examples).
    + Key money requires legal advice.
    + Line waiting time.
    + ...
+ The loss of welfare from buying or selling close substitutes
    + Car trip instead of flying
    + Sharing a house instead of your own apartment.


## Tax

+ You can use welfare analysis to look at taxes too.
+ Simple excise tax on a market.  We are not looking at income tax but it can be similar.
+ The social cost of the tax is greater than the revenue.
+ The institution of 'who writes the check' determines the price on the shelf but not relative shares of the tax -- *the burden of the tax*
+ Who pays, *the burden*, depends on relative price sensitivity of buyers and sellers.

## The two institutions

+ "Buyer Writes The Check"
    + You buy the item 
    + Pay the tax after you pay the seller (Like sales tax).
    + Looks like a decrease in demand
+ "Seller Writes The Check"
    + You buy the item
    + Tax is included in the price.
    + Looks like a decrease in supply
    
    
## Buyer Writes Check


## Things to Spot

+ The buyers pays a higher price
+ The seller gets a lower price
+ The shelf price changes with the institution but not who gets and pays what.
+ The gap is the per-unit tax
+ The deadweight loss has a special name "excess burden"
+ The gap has a special name "Tax Wedge"

## Seller Writes Check

## Things to Spot

+ The buyers pays a higher price
+ The seller gets a lower price
+ The gap is the per-unit tax

Yes, it is all the same!

## Close Look at the Tax Burden

+ Stick with the seller writes the check version but can show this either way.
+ Compare the changes in consumer and producer surplus with and without a tax.

## Seller is relatively sensitive to price changes


## Seller is relatively insensitive to price changes


## Things to Spot

+ "who pays" is not about institution but about sensitivity to prices.
+ The party least willing to change behavior when price changes, has the larger burden
+ There is more deadweight loss, loss to society, when transactions change a lot.

## On Excess Burden

+ Lots of excess burden on luxuries
+ Little excess burden in necessities

Ethics?

## Next Up

Ch 6: Elasticity
