---
title: "Production"
output: beamer_presentation
theme: "Berlin"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Goals

+ Create a taxonomy, i.e., a categorization, of productive inputs
+ Show a general pattern of production and why those patterns happen.
+ Use a production function to derive common cost functions: AC, MC, AVC, AFC, etc.


Warning: Things will be getting mathy and graphy.

## The Hot dog Stand

+ Actual hot dog stand on the Santa Cruz Boardwalk in the 70s.
+ Really small
+ Very experimental person running it.


## The Stand and Things in it


## Inputs

+ All the things, tongs, bottles, buns, kimchi, are *inputs*.
+ Those divide into two groups:

    + *Fixed inputs*, Capital (K): Don't change when output changes.  Are uncorrelated with output. (The building, tongs, steam trays, ...)
    + *Variable inputs*, Labor (L): Change when output changes.  Are correlated with output.(The buns, kimchi, mustard, people working,...)
    
We will bundle the variable inputs into one and call it labor minutes.  "Labor" and "Capital" are convention.

## Add People and Plot What is Made


## Observe

+ No variable inputs, no outputs.
+ Add variable inputs and output goes up, but eventually falls.
+ Each worker add more to output than the previous for a while.
    + Increasing *marginal product of labor*
    + For calc people $\frac{\partial^2}{\partial x^2} > 0$
+ Each worker then adds more to output, but the increase of each new worker is less than the last.
    + Decreasing *marginal product of labor*
    + For calc people $\frac{\partial^2}{\partial x^2} < 0$
+ Ignore the part where we make output go down.  It is silly.

## Why Increasing and Decreasing $MP_L$?

+ Increasing $MP_L$, output increases and last added adds **more** than the previously added.
    + Less idle capital but labor in constant motion.
    + More specialization.
    + Learning by doing (Slightly off)

+ Decreasing $MP_L$, output increases and last added adds **less** than the previously added.
    + No idle capital but labor not in constant motion.
    + No more gains from specialization on this scale.
  
## Our Clean Idealized Production Function


## Lets Turn this Into Costs

+ Invert production function, $f(input) = output$ to get **inverse production** function, $f^{-1}(output) = input$.
+ Multiply inverse production function by price of variable input, wages, $w$ to produce **variable cost function**, $wf^{-1}(output) = w input = VC(output)$.
+ Add cost of fixed inputs, $r$, to produce **total costs**, $VC(inputs) + rK = VC(output) + rK = VC(output) + FC = TC(Output)$

## Inverting with Mirrors and Pipe cleaners


## Multiply by Stretchering

## Add by Sliding


## Great, but We Need More

+ Eventually we will find the output that maximizes profit.  
+ Calc people know that means take a derivative.
+ Will do this graphically but we need more cost functions.

## The Average Family

$$\frac{g(x)}{x} = Average~G~Function$$

+ Will put a variety of costs in for $G$.
+ AFC: Average fixed cost
+ AVC: Average variable cost
+ AC or ATC: Average Cost or Average Total Cost

## The Marginal

+ For calc people, $\frac{\partial TC}{\partial q} = \frac{\partial TC}{\partial q} = MC(q)$
+ For non-calc, the **additional** costs required to produce one more.


## Cord from Origin Trick on AFC


## Construct AVC


## Construct AC

## Construct MC

## All the Average/Marginal at Once

## Key Features

+ AC generally like a smile but can have other shapes IRL
+ Mark the min of AC
+ MC looks like a Nike swoosh/fish hook that cuts min of AC.
+ AVC is less than AC, is cut at min by MC, and gets closer and closer to AC as output increases. ***THIS IS THE HARD PART***
+ Note hidden AFC, the vertical distance between AC and AVC.

## A Few Rules

+ FC is fixed
+ $TC = VC + FC$
+ $VC(0) = 0$
+ $AC = AVC + AC = \frac{TC}{Q} = \frac{VC}{Q} + \frac{FC}{Q}$
+ $MC(Q) = TC(Q+1) - TC(Q) = VC(Q+1) - VC(Q)$ The non-calc definition varies by textbook.  Caution.


## Try a Table

Q    | TC      | VC    | FC   | AC   | AFC   | AVC | MC  |
---  |---      |---    |---   |---   |---    |---  |---  |
0    |         |       |      |      |       |     |  3  |
1    |         |       |  2   |      |       |     |     |
**4**|  15     |       |      |      |       |     |  x  |

##  So now what?

At this level, economics has a specific modus operandi 

+ Figure out what the actor wants, the objective function.
+ Figure out the constraints, costs, income, ...
+ Maximize (or minimize) the objective function subject to those constraints.

We will assume that the goal of the firm is profits, $\Pi$, which we define as revenue less costs.

## Warning

+ Costs are more expansive to an economist.
    + We include opportunity cost.
    + Imputed salary of owner that takes no salary.
    + Impute rent when firm owns property, even things like desks
+ Because Costs are Different -- Profits are different.
    + Net Income, profit to an accountant, is always more than economic profit.
    + We include costs they don't
    
## Implication

$$Accounting~Profit - Opportunity~Costs = Economic~Profit$$

Just because you have positive accounting profits, net income, does not mean you have positive economic profits
    
## Profit

$$\Pi = Rev(q) - Cost(q)$$

+ Positive profit 
    + Greater than can be achieved elsewhere in the economy for the same risk.
    + Expect net entry soon
+ Zero or Normal Profit
    + Equal to what can be achieved elsewhere for the same risk.
    + No net entry or exit
+ Negative: Less
    + Net exit

Note that risk is built in.  The higher the risk the more profit needed.


## Example

+ A very safe 2% return may be positive economic profits.
+ A very risky 15% return may be negative economic profits.


## So what Does the Firm do?

Competitive firms observe a price and choose output to maximize profit.

+ They can't control price and can only react.
+ Profit, not maximum per unit.
+ Calc people will see this as an optimization problem.

## Forget this formula

$$\max_q R(q) - C(q)$$

## Profit Max Q with Total Cost and Total Revenue


## Profit Max Q with Average and Marginal Costs

## Steps

+ Find $q^*$ where $MC = MR$
+ Start at $q^*$ go to AC and hang a left.  
    + That is $AC^*$.
    + Box is Total Cost, $TC^* = AC^* q^*$
+ Start at Start at $q^*$ go to $AR=P=MR=D_{firm}$ and hang a left.  
    + That is $AR^*$.
    + Box is Total Revenue, $TR^* = AR^* q^*$
+ Little box on top is profit.

Weird sunglasses shows up when there is positive economic profits.


## Negative Economic Profits

## Negative Profits

+ No Weird sunglasses thing but a funny triangle.
+ Does not mean you go out of business or exit.
    + But you could make more in another industry.
+ There is a shut-down condition
    + If AVC > AR, shut down
    + Not out of business.
+ Why all stores are not 24/7.
    + The revenue from staying open (AR) is less than the costs of lights and labor (AVC).
    + Exit and Entry is a long term topic which we handle elsewhere.
    
## Why Shutdown?

$$\Pi = TR - FC - VC$$
When TR<VC you are better off just paying FC and let $TR=0$ and $VC=0$.

$$\Pi = (TR - VC) - FC < -FC$$

## Play Time

+ Which curves move when price changes?
+ Which curves move when the rental rate, r, the price of fixed inputs changes?
+ Which curves move when the wage rate, w, the price of the variable input changes?

## Price?

+ No cost curves change
+ $q*$ changes and everything that follows after that.
+ MC is the supply curve for the firm


## Price Demo

## Change the Rental Rate

Double the rental rate

Q    | TC      | VC    | FC   | AC   | AFC   | AVC | MC  |
---  |---      |---    |---   |---   |---    |---  |---  |
0    |    2 (4)     |  0     |  2 (4)   |      |       |     | 1   |
1    |    3 (5)    |   1    |  2 (4)  |  $\frac{3}{1}$ ($\frac{5}{1}$)     |  $\frac{2}{1}$ ($\frac{4}{1}$)     |  $\frac{1}{1}$    |   x  |

+ TC, FC, AC, AFC change
+ MC, VC Don't


## Diagram


## Note

+ $q^*$ does not change
+ Revenue does not change
+ Profits change


## Change the Wage Rate

Double the rental rate

Q    | TC      | VC    | FC   | AC   | AFC   | AVC | MC  |
---  |---      |---    |---   |---   |---    |---  |---  |
0    |    2      |  0     |  2    |      |       |     | 1 (2)   |
1    |    3 (4)    |   1  (2)  |  2   |  $\frac{3}{1}$($\frac{4}{1}$)     |  $\frac{2}{1}$      |  $\frac{1}{1}$ ($\frac{2}{1}$)    |   x  |

+ TC, VC, AC, AVC and MC change
+ FC and AFC Don't


## Diagram (TRICKY)


## Note

+ $q^*$ does change
+ Revenue changes
+ Profits change

## What You Learned So Far

+ MC is the supply function for the firm.
+ Wage changes moves MC the same way supply changes  in S/D model
+ Rental rate does not right now but will in next section, Long-run perfect competition.