---
title: "Video Links"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Math

**Read Graphs in Economics CH2 appendix except for "Calculating the slope along a nonlinear curve."**

adding fractions
https://youtu.be/bcCLKACsYJ0

Multiply
https://youtu.be/hr_mTd-oJ-M


area rectangle
https://youtu.be/mu3HHCdYYtY

area triangle
https://youtu.be/rRTXKQpblEc

Slope of a line
https://youtu.be/R948Tsyq4vA

Slope intercept form graph
https://youtu.be/IL3UCuXrUzE

Find slope and intercept from equation
https://youtu.be/xGmef7lFc5w

solve system (1)
https://youtu.be/NPXTkj75-AM

Solve system (2)
https://youtu.be/2EwPpga_XPw

## Ch 1

**Read All Ch 1**
Normative vs positive https://youtu.be/YtX6SGw7E3c

## Ch 2 PPF

**Read chapter except "Transactions: The Circular -Flow Diagram"**

What is PPF
https://youtu.be/_7VHfuWV-Qg\

Oportunity costs and ppfs
https://youtu.be/pkEiHZAtoro

Increasing opportunity cost
https://youtu.be/00fgAG6VrRQ

Increasing decreasing costant opportunity cost.
https://youtu.be/-aVZtzD44vI

Specialize and gains from trade
https://youtu.be/xx9xNJlPOJo


Comparative and Absolute
https://youtu.be/xN3UV5FsBkU

Comparative and abosolute with a table
https://youtu.be/K8p0F92gVUM

Worked PPF trade problem
https://youtu.be/jHp4fnrEA6w

## Ch 3 Supply and Demand

**Read All Ch 3**

Demand
https://youtu.be/ShzPtU7IOXs

Supply horizontal summation
https://youtu.be/dGjPguqHBXE


Part of shifting demand subs and complements
https://youtu.be/-oClpRv7msg

Future prices Demand
https://youtu.be/7siSvYs84fg

Income pop taste
https://youtu.be/do1HDIdfQkU

Normal and inferior example
https://youtu.be/wYuAwm-5-Bk

Law of Supply
https://youtu.be/3xCzhdVtdMI

Change in supply vs quanity supplied
https://youtu.be/NrlF8mMHfLE


Equilibirum adjustment
https://youtu.be/PEMkfgrifDw

The four one shock equilibirum changes
https://youtu.be/NgPqyM3I_8o

Two shocks but missing summary
https://youtu.be/kl4n-EWwPyA

## Ch 4 CS and PS

**Read all Ch 4**

MB interpretation of demand
https://youtu.be/KrkbbRxdDZ8


CS introduction
https://youtu.be/_6kwhF6hoqQ

CS area
https://youtu.be/RBUBIRtn0xQ


PS area
https://youtu.be/-V-Y5klejSg

Competitive equalibrium equalizes
https://youtu.be/E_EmGO1XuHM


## Ch 5 Price and quanity controls
**Read all ch 5**

Price Ceiling CS/PS (rent control)
https://youtu.be/8U8egQjcPaI

Price floor minimum wage 
https://youtu.be/j0c2vmFGbtk

quanity constraint max
https://youtu.be/-T8lzuTwdbI


## Ch6: Elasticity

**Read Ch6 except "An Alternative Way to Calculate Elasticities:  The Midpoint method"**

Good intro to demand
https://youtu.be/FBWJYH8DZ1g

Determinants of income elasticity
https://youtu.be/KEhy6SwW__I

Perfectly elastica and inelastic
https://youtu.be/6udRtn5jSWk

Constant elasticity demand
https://youtu.be/m7qXvQvWlY4

Expenditures and elasticity
https://youtu.be/Udltkvm9HLc

More on expenditures and elasticity
https://youtu.be/KgrLUQYgIJE

Elasticity of supply
https://youtu.be/wi1x3sYHU6I

Income elasticity
https://youtu.be/RDcf5L6o0mI

cross price
https://youtu.be/Ngv0Be9NxAw


## Ch 7 Taxes
**Read all ch 7**

CS/ps tax
https://youtu.be/NuLlNAdrom4

Perfectly inelastic demand tax
https://youtu.be/lsn16U5DWD4

Tax perfectly elastic
https://youtu.be/z1yJPpGC3-o


##Ch 11: Behind the supply curve

**Read ch 11 up to "Short-run versus Long-Run Costs"**

Production

Production function introduction
https://youtu.be/4kFLOoA5l4s

TP, MP and AP with tables
https://youtu.be/8fm9FjDV0iA

Fixed variable and marginal cost example
https://youtu.be/bBQVaRnHqLs

table cost
https://youtu.be/mW6Cwpfb5CI

Changing w table
https://youtu.be/dbedc5rrwhQ


Chnage W graphical
https://youtu.be/A1_PT1aHVLY


## Ch 12 Perfect competition

**Read Ch 12**

Econ profit vs accounting
https://youtu.be/06j_zPdPWOY

Profit maximiation output PC
https://youtu.be/SON0BtLMUHw

Shut down condition
https://youtu.be/aPiZloqtlnc

Long run in PC extensive
https://youtu.be/Xx5-O8kDMvU


PC Explicitly

Profit possitive negative vs price
https://youtu.be/JWuWzloEH40

PC LR
https://youtu.be/Xx5-O8kDMvU


## Ch 13 Monopoly
 **Read all ch 13**

Monopoly


MR with market power (poorly motivated)
https://youtu.be/A-uVHlqEiyE

profit in monopoloy
https://youtu.be/PEFEnss--mU

Total revenue function monopoly
https://youtu.be/cczABrLd_uA

Maximizing profit MR and Marginal profit
https://youtu.be/s1UQQELPyrc

Monopoly dwl
https://youtu.be/daxL1ZLrUzg

## Ch 15 Monopolistic competition

**Read all ch 15**

## Ch 16 Externalities

**Read all ch 16**

Negative externality goods market
https://youtu.be/nBw6KvU51BE

Possitive externalities goods market
https://youtu.be/TSTLLFJbaA4

Pigouvian tax in goods market
https://youtu.be/UYShebe44Xs


## Ch17 Public Goods
**Read all ch 17**
Commons in pictures not graphs
https://youtu.be/0b2Tl0x-niw

Rival excludable the fourby table
https://youtu.be/pJU028t-7mg
