---
title: "Syllabus EC 201 Fall 2022"
author: "James Woods"
date: ""
output: pdf_document
fontsize: 12pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Course Description

The official description of the course is:

 > A study of the choices individuals face as participants in the markets for goods, services and factors of production like labor; behavior of profit-maximizing firms operating in markets with varying degrees of competitive pressure; potential role of government in intervening to influence market outcomes using taxes and subsidies; reasons for international trade and economic inequality.

It is my intent to give you a basket of tools that you can use to better understand the news, your later economics courses, and how small differences in institutions can dramatically change the choices we make.

students approach the course, and college, a few different ways and we provide a few different ways you can approach the course.

You can take this as a *proficiency based course* with a top grade of C+ (B- with extraordinary effort), or as a *written exam based course* with a full A to F grading scale. Full details on both are given below and will be described in class.

The intent is that if you are only taking the class because you need it for a degree requirement, true for business students, and are not interested in the material, you can take the proficiency based version, which *can be, but should not be, done online without attending class*.

If you are more interested and are willing to learn the material beyond recognition stage, if you intend on majoring in economics, or are really looking for an A in the course, go for the exam-based version of the course.

## Technology Requirements

It is assumed that you can access the class via zoom and have a functioning web browser that can access google docs when you are logged in on your @pdx.edu account.  The slides are interactive and assume you have some kind of touch or pseudo-pen interface. You could use your finger and your phone (which works but I would not recommend), a computer with a touch screen, or even a small \$30 Wacom tablet.

The technology requirements are your responsibility. 

# Contact Information

Communication will be handled through slack <http://woodseconomics.slack.com/>. You should have received an invitation, if not, just go to that URL and use this link (**JOIN LINK HERW**) and your @pdx.edu email to sign up. There are reasonable help documents to get you started (<https://get.slack.help/hc/en-us/articles/218080037-Getting-started-for-new-users>)

Slack will be used for IM, email and forum style communication. It even handles phone and video calls. If you have a question about course material or the course itself, ask in one of the channels, e.g., \#macro_general. If you have a personal message that is not intended for others, send a direct message, i.e., @woodsj.

Office Hours:

-   Zoom office hours are Monday 3:30-5:30pm and Tuesday 10:00-11:30. There are no office hours final exam week.  
-   You can schedule one-on-one meetings at <https://woodsj.youcanbook.me/>. These will be online meetings through zoom.

# Basis for Grade

I provide two ways to take this course:

-   **Proficiency based**: No written exams and a maximum grade of C+ (or a B- with extraordinary effort.) based on modules completed at an acceptable level.  Acceptable is generally 70% depending on the module.  This is not a high bar.

-   **Exam based**: Four written exams.

The proficiency based system is intended for non-majors or those that have limited time to devote to this course given their other commitments. Please understand that the maximum grade you can earn is a C+ (or a B- with some extraordinary effort). This keeps you in good academic standing and the overall effect on your GPA is negligible.

The exam based system is more difficult, but you will have a solid understanding of the material for later courses and life.

Your choice will probably depend on the time you have available for the course and your study habits.

The modules and quizzes will be open for both groups and you will see the results of the auto-graded quizzes and hand-graded questions.

**The module based quizzes only count for those in the proficiency based track.**

## Basis for Grade: Proficiency Based

Your grade in the class will be determined by the number of modules you complete at an acceptable level. The more modules you complete, the higher your grade.

Quizzes for each module will be available for three weeks. There will generally be an adaptive quiz, which you can take at any time once it is available. You need a minimum score on the adaptive quiz before the fixed quiz opens. **The adaptive quizzes can take anywhere from 15 minutes to forever.**  

You can take the fixed quiz once per week in each of the three weeks it is open. This does not mean that you get three tries. If your first attempt is on the last available week -- you get one attempt. **The fixed quizzes should take between 30 minutes to an hour to complete but you will be given 1:30.**

Acceptable adaptive and fixed quiz scores may be determined either before or after students take the quizzes.

-   B-: 12 Modules
-   C+: 9 Modules
-   C: 7 Modules
-   P: 7 Modules
-   D: 5 Modules

## Basis for Grade: Exam Based

This is intended to give students the kind of experience you would get at a liberal arts college and better prepare students that intend on majoring in economics.

Your grade is determined completely based on your performance on the in-class written exams and periodic homework.

The quizzes used by those on the proficiency track are just for practice and are not part of your grade. You will still see those scores, and we will still give you feedback on your work, but it won't count for your grade.

There are three midterms and a final exam. We will sit these in class.

We can adapt this to a remote exam, but expect to have your camera on and have a useful pen or stylus interface through tablet or other touch screen device sufficient to use jamboard (<https://jamboard.google.com>).

The exams will be a mix of problem solving, math type questions, and some essays. You will have some of the material for these exams ahead of time, mostly some question possibilities for the essays, and some short news readings to interpret. 

I will pin a current list of questions in slack.

The first midterm is purposefully weighted low so you don't walk out of thinking you have ruined your grade -- you have not. The intent is to give you an easy introduction, or reintroduction, to this kind of approach to learning.

-   Midterm 1 (Week 3, Jan 19): 10%
-   Midterm 2 (Week 6, Feb 9): 30%
-   Midterm 3 (Week 8, Feb 23): 30%
-   Final Exam (Final Exam Week, March 15 8:00-9:50): 30%

You must take all exams for a passing grade.

## Which Path, Proficiency Based or Exam?

From my point of view it is easy. If you turn in Midterm 1, you are on the exam path. If you don't, then you are on the proficiency based path.

You can't change back to proficiency based after you turn in an exam, and you can't switch to exam based after you skipped the first midterm.

My recommendation is to start the class planning to do all the modules, which if you are on the exam path you should do anyway, and then show up on exam day and make the decision after you see the exam.

If you turn in the exam -- you are on the exam path. The modules no longer count for your grade, but keep doing them because they are really helpful.

## What Ifs

-   Q: What is the worst thing you see a student doing with this system? A: I see students not doing the modules, for whatever reason, tempted by only having to do four exams on four days, and then being able to do nothing on the exam.

-   Q: What if I change my mind about the grade option later in the term? Can I make up the exams or go back and do extra modules? A: No. It is a one-way door.

-   Q: What if I am on the *proficiency based* system and I get sick? A: It depends on how severe it is. If it is something mild, less than two weeks, you can catch up on the material in the third week. If it is severe, longer than two weeks, you can make a deadline appeal <https://www.pdx.edu/registration/DAC>. You must send documentation, but it removes the course from your transcript and gets you your money back.

-   Q: What if I am on the *exam based* system and I get sick on exam day? A: It depends on how severe. If you can work, but should not be on campus, take the exam remotely. If it is more severe than that, you can do one, and only one, *make-up exam on DATE NEAR END OF TERM*. If you are sick on make-up exam day and have a passing grade, we can give you an incomplete, if not, you can make a deadline appeal <https://www.pdx.edu/registration/DAC>. You must send documentation, but it removes the course from your transcript and gets you your money back.

# The In-class Experience

I am anticipating that some of the class will be joining our meeting in-person and some remotely. This class is built to be fully remote if things get odd.

## Regular Lecture Days

I'll have zoom up on my laptop, but I'll just have the microphone on. The the in-class material will be a combination of Google slides, which I will share with you and perhaps a jamboard for problem solving. This should work a lot better for those with with slower computer processors and less memory. Zoom video eats cpu cycles.  

The slides will be shared with you and will stay synced with where we are in class. I won't be screen sharing; it will just automatically sync.  This makes it much easier to join by phone without running zoom in the background.

There will also be a lot of collaborative elements to these slides. I may ask you to draw a diagram of a domestic market with imports and I will be able to see what each of you do.  This is why the psudo-pen interface is important. [^2]

[^2]: Pear Deck (<https://www.peardeck.com>) is driving this if you are curious.

Stay alert. Stay engaged.  And I will send feedback via email on what you did in class the next day.

There are no participation points.  You don't get credit for showing up, or logging onto zoom.  Showing up to class is just about the most important thing you can do to be successful. I'm just not gamifying it with points.

## Exam Days

You have had a copy of some of the questions or possible questions for a few days.  You should have outline and sketch answers for these as part of your preparation.  That is just advice; I don't recommend walking into the exam blind.

On exam day you are feeling pretty good and show up to class.  You get your personal copy of the exam, which could be different from the others.

The exams will be diagram heavy and there will not be any multiple choice questions.  The exams will be scaled, so don't get alarmed about scores.  Three out of five on a question may be a great score.

The exams are designed to be take anywhere.

You will be on zoom with your camera and microphone on and you will receive a Google doc when the exam starts with your questions, which could be different from the others. You can type your answers and open the linked jamboard for figures, diagrams and math answers.

# Textbook and Other Resources

I have assigned Krugman, Paul R., and Robin Wells. Microeconomics ed. 6., Worth Publishers. The text is bundled with quizzes and homework assignments and you should be able to purchase the whole package through Canvas.


1. Math:  You need Freshman High School Algebra for this class. This is one of the biggest stumbling blocks.

1. What is Economics (Ch 1):  It is bigger than you thought and even helps explain small behaviors.

1. The Basis for Trade and PPFs (Ch 2):  There are very good reasons make somethings yourself and to buy others.  

1. Supply and Demand (Ch 3):  What everyone knows.  This is a good simple model for many things, but not everything.

1. Consumer and Producer Surplus  (Ch 4): This is one of the ways economists measure welfare, how well off people are not free money.

1. Price and Quantity Controls (Ch 5):  Sometimes you can make people better off by constraining price and sometimes you make people worse off,

1. Elasticity (Ch 6):  A measure of how flexible people, businesses and other institutions are to changes, including price and income changes.

1. Taxes (Ch 7):  Taxes are a source of revenue for public services, but they can also be used to cure problems in markets.  Who pays for taxes  is less clear than you thought.

1. Behind Supply Curves (Ch 11): Not all markets, choices, or allocation mechanisms can be described by supply and demand.  Cost curves allow us to find out what happens in those circumstances.

1. Perfect Competition (Ch 12) :  We prove to ourselves that we can use cost curves to describe what happens in perfect competition, when markets are the right tool for the job.

1. Monopoly (Ch 13): Uses cost curves to describe the costs to society of market power.

1. Monopolistic Competition (Ch 15):  The most common market structure you interact with.  If it has a prominent brand -- its monopolistic competition.

1. Externalities (Ch 16) :  This is where economist spend much of their time. We will use tools to figure out how to do things like reduce air pollution and traffic to were the benefits to society are as large as possible.  

1. Public Goods (Ch 17):  There are some goods we share -- like parks, roads, national defense. Deciding how much of these shared goods around is more complex that figuring out how many cups of coffee to drink.

# Policy Statements from the University

+ **PSU Grading System Undergraduate**: http://pdx.smartcatalogiq.com/2021-2022/Bulletin/Undergraduate-Studies/Grading-System-for-Undergraduates 

+ **Drop/Withdraw Deadline**: http://pdx.smartcatalogiq.com/en/2021-2022/Bulletin/Academic-Calendar

+ **Academic Integrity**: Academic integrity is a vital part of the educational experience at PSU. Please see the PSU Student Code of Conduct for the university’s policy on academic dishonesty. A confirmed violation of that Code in this course may result in failure of the course.

+ **Incomplete Policy**: Students do not have a right to receive or demand an Incomplete grade. The option of assigning an Incomplete grade is at the discretion of the instructor when the following criteria are met. Eligibility Criteria:

  1.	Required satisfactory course completion/participation. 
  2.	Reasonable justification for the request. 
  3.	Incomplete grade is not a substitute for a poor grade. 
  4.	Written agreement. (See Incomplete Contract)
  5.	Resolving the Incomplete. 



+ **Student Services Disability Access Statement**: If you have, or think you may have, a disability that may affect your work in this class and feel you need accommodations, contact the Disability Resource Center to schedule an appointment and initiate a conversation about reasonable accommodations. The DRC is located in 116 Smith Memorial Student Union, 503-725-4150, drc@pdx.edu, https://www.pdx.edu/disability-resource-center/ .

+ **Safe Campus Statement**: Portland State University desires to create a safe campus for our students. As part of that mission, PSU requires all students to take the learning module entitled Creating a Safe Campus: Preventing Gender Discrimination, Sexual Harassment, Sexual Misconduct and Sexual Assault. If you or someone you know has been harassed or assaulted, you can find the appropriate resources on PSU’s Enrollment Management & Student Affairs: Sexual Prevention & Response website at http://www.pdx.edu/sexual-assault

+ **Student Food Security** :Any student who has difficulty affording groceries or accessing sufficient food to eat every day, or who lacks a safe and stable place to live, and believes this may affect their performance in the course, is urged to contact Committee for Improving Student Food Security for support at foodhelp@pdx.edu. Furthermore, please notify the professor if you are comfortable in doing so. This will enable her to provide any resources that she may possess.

+ **Title IX Reporting**: As an instructor, students frequently come to me for assistance in matters that are not related to the course material. Please be aware that PSU’s policies require instructors to report any instance of sexual harassment, sexual and relationship violence and/or other forms of prohibited discrimination to University Officials, who keep the information private. If you would rather share information about these experiences with a PSU staff member who does not have these reporting responsibilities and can keep the information confidential, please contact one of the following campus resources.
  + Confidential Advocates: 503.894.7982, or by scheduling online (for matters regarding sexual harassment and sexual and relationship violence)
  + Center for Student Health and Counseling (SHAC): 1880 SW 6th Ave, 503.725.2800
  + Student Legal Services: 1825 SW Broadway, (SMSU) M343, 503.725.4556 For more information, please complete the required student module Understanding Sexual Misconduct and Resources in D2L.
PSU Sexual Misconduct Response website gives you comprehensive information about how to support and/or report an incident. Please complete the required student module Understanding Sexual Misconduct and Resources, which provides information about PSU policy and resources.



+ **Cultural Resource Centers**: The Cultural Resource Centers (CRCs) create a student-centered inclusive environment that enriches the university experience. We honor diversity, explore social justice issues, celebrate cultural traditions, and foster student identities, success, and leadership. Our centers include the Multicultural Student Center, La Casa Latina Student Center, Native American Student & Community Center, Pan African Commons, Pacific Islander, Asian, Asian American Student Center and the Middle Eastern, North African, South Asian program. We provide student leadership, employment, and volunteer opportunities; student resources such as computer labs, event, lounge and study spaces; and extensive programming. All are welcome!


+ **Recording Technology Notice**: We will use technology for virtual meetings and recordings in this course. Our use of such technology is governed by FERPA, the Acceptable Use Policy and PSU’s Student Code of Conduct. A record of all meetings and recordings is kept and stored by PSU, in accordance with the Acceptable Use Policy and FERPA. Your instructor will not share recordings of your class activities outside of course participants, which include your fellow students, TAs/GAs/Mentors, and any guest faculty or community-based learning partners that we may engage with. You may not share recordings outside of this course. Doing so may result in disciplinary action. 

+ **Turnitin**: Students agree that by taking this course all required papers may be subject to submission for textual similarity review to Turnitin.com for the detection of plagiarism. All submitted papers will be included as source documents in the Turnitin.com reference database solely for the purpose of detecting plagiarism of such papers. Use of Turnitin.com page service is subject to the Usage Policy and Privacy Pledge posted on the Turnitin.com site. 





Link to this syllabus https://github.com/woodsjam/Course-Intro-Microeconomics.  There is a branch for each term with master being the current term.
