---
title: "Monopoly"
output: beamer_presentation
theme: "Berlin"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

##  Goals

+  Define and look at the effects of monopoly.
+  Use as a general model for what happens when there is market power.
+ Get through the uglyist graphs in EC 201


## Monopoly Key Assumptions

The same as perfect competition except:

+ There is only one seller
+ The seller engages in price setting behavior.
    + In PC, firms observe price and then choose quantity to maximize profits.
    + In Monopoly, firms observe demand and then choose quantity and let the price adapt.
+ No entry or exit.  Technically you only need no entry but no exit makes this simpler.

## Monopolies are

Don't think of monopolies as being globe spanning huge corporations.  Monopoly power often simpler.

+ The only gas station in a small geographically isolate town.
+ The only provider of a drug needed for a medical condition.
+ Local newspaper/radio or TV station for local news.
+ Sometimes the best answer to a problem, but we regulate those.


## How can I get one?

+ Geographic isolation
+ Barriers to entry
+ Control of a unique resource -- Rich minerals, a face, knowledge
+ Government grants it to you -- franchise
+ Intellectual Property -- Patent, copyright.
+ Large economy of scale -- like natural gas distribution
+ Network externalities  -- non-standard connectors 


## What is different About the Analysis?

+ In perfect competition, $MR= AR= P = D_{firm}$.
+ In monopoly (Single price), MR splits off.
+ Because of no entry or exit -- no long-run analysis on extensive margin.  Plenty happens on intensive but wait till EC 311/415 for that.


## Marginal Revenue

The additional revenue from selling one more unit.

+ This is price in perfect competition.
+ $MR<Price$ in monopoly because to sell one more, you must reduce price on all units sold.

## Math For Calculus Folks

Assume a linear demand, $P = P_0 - \alpha q$

$$R(q) = P q = (P_0 - \alpha q) q=P_0q - \alpha q^2$$

The derivative of revenue is marginal revenue

$$MR(q) = \frac{\partial}{\partial q}R(q)= P_0 - 2 \alpha q$$

Same intercept but twice as steep.


## Build MR Graphically

## Key Takeaways

+ Same intercept but twice as steep.
+ Marginal revenue can be negative.  
+ Revenue, not profit, is maximized when $MR = 0$.


## Steps

These are the same as Perfect Competition.

+ Find $q^*$ where $MC = MR$
+ Start at $q^*$ go to AC and hang a left.  
    + That is $AC^*$.
    + Box is Total Cost, $TC^* = AC^* q^*$
+ Start at Start at $q^*$ go to $AR=D_{firm}$ and hang a left. 
    + That is $AR^*$.
    + Box is Total Revenue, $TR^* = AR^* q^*$
+ Little box on top is profit.


## Monopoly Graphs

## Why Monopoly is Bad

+ Price and quantity effects
    + Price is higher
    + Less is sold
+ Welfare Effects
    + DWL
    + Reduction in CS
+ Long-run Effects
    + Price and cost above marginal cost
    
    
## Price and quantity effects

## Welfare Effects

## Long-run Effects

## But, sometimes we need a monopoly

Minimize fixed costs for things like local electricity and natural gas distribution.

+ Why have two conduits or service heads to your house when you only need one.
+ In this case the monopolist has lower costs but still charges higher prices.
+ We regulate these firms. This is in EC 437 Public Utility Economics.


## Example

+ We call this a natural monopoly
+ Fixed cost but MC is constant  $C(q) = F + \beta q$.
+ Cost of one firm to produce $F + \beta q$
+ Cost of two firms $(F + \beta q/2) + (F + \beta q/2) = 2 F + \beta q$
+ Twice the fixed cost

## Up next

Depending on timing, brief Monopolistic Competition and then externalities and public goods.