---
title: "Monopoly and Monopolistic Competition Worked"
output: beamer_presentation
theme: "Berlin"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Monopoly Key Assumptions

The same as perfect competition except:

+ There is only one seller
+ The seller engages in price setting behavior.
    + In PC, firms observe price and then choose quantity to maximize profits.
    + In Monopoly, firms observe demand and then choose quantity and let the price adapt.
+ No entry or exit.  Technically you only need no entry but no exit makes this simpler.

## Monopolies are

Don't think of monopolies as being globe spanning huge corporations.  Monopoly power often simpler and smaller.

+ The only gas station in a small geographically isolate town.
+ The only provider of a drug needed for a medical condition.
+ Local newspaper/radio or TV station for local news.
+ Sometimes the best answer to a problem, but we regulate those.

## The Keys

+ Entry is somehow blocked or hard to do.
+ There are no close substitutes
+ The firm can control price.

## How can I get one?

+ Geographic isolation
+ Barriers to entry
+ Control of a unique resource -- Rich minerals, a face, knowledge
+ Government grants it to you -- franchise
+ Intellectual Property -- Patent, copyright.
+ Large economy of scale -- like natural gas distribution
+ Other Cost/Quality advantage
+ Network externalities  -- non-standard connectors, social media platforms 


## What is Different About the Analysis?

+ In perfect competition, $MR= AR= P = D_{firm}$.
+ In monopoly (Single price), MR splits off.
+ Because of no entry or exit -- no long-run analysis on extensive margin.  Plenty happens on intensive but wait till EC 311/415 for that.


## Marginal Revenue

The additional revenue from selling one more unit.

+ This is price in perfect competition.
+ $MR<Price$ in monopoly because to sell one more, you must reduce price on all units sold.

## Math For Calculus Folks

Assume a linear demand, $P = P_0 - \alpha q$

$$R(q) = P q = (P_0 - \alpha q) q=P_0q - \alpha q^2$$

The derivative of revenue is marginal revenue

$$MR(q) = \frac{\partial}{\partial q}R(q)= P_0 - 2 \alpha q$$

Same intercept but twice as steep.

## Graphically

## Similar but in Table form

Quantity| Price     | TR    |MR             |
---     |---        |---    |---            |        
1       |20         |       |               |
2       |18         |       |               |
3       |15         |       |               |
4       |5          |       |               |



## Key Takeaways

+ Same intercept but twice as steep.
+ Marginal revenue can be negative.  
+ Revenue, not profit, is maximized when $MR = 0$.

Note that in a table, you don't always see MR =0 or even MR = MC.  Integers are funny that way.

## Profit Maximizing Output

These are the same as Perfect Competition.

+ Find $q^*$ where $MC = MR$
+ Start at $q^*$ go to AC and hang a left.  
    + That is $AC^*$.
    + Box is Total Cost, $TC^* = AC^* q^*$
+ Start at Start at $q^*$ go to $AR=D_{firm}$ and hang a left. 
    + That is $AR^*$.
    + Box is Total Revenue, $TR^* = AR^* q^*$
+ Little box on top is profit.


## Monopoly Graph (Positive Profit: D cuts AC twice)

## Monopoly Graphs (Negative Profit: D never cuts AC)

## Can you Find DWL?

## Why Monopoly is Bad

+ Price and quantity effects
    + Price is higher
    + Less is sold
+ Welfare Effects
    + DWL
    + Reduction in CS
+ Long-run Effects
    + Price and cost above marginal cost

## But We Need it Sometimes

+ There is an argument for a monopoly when they can produce for less than multiple competitive firms
    + AC = K/q, just fixed cost and no variable cost
    + AC =10/q, a specific one
    + Suppose we need 10
    + One firm AC = 1
    + Two firms AC = 5/10 =2

Why there is only one local electricity or natural gas distribution company in your area.
    
## IRL    
    
+ We typically have these publicly owned, water for example.
+ Simulate the pressure of a market with price regulation.  This is what the Public Utilities Commissions do.


##  Monopolistic Competition

Old model from the 1930s and before game theory.  Probably the most common market.


If you can remember a brand, it is probably monopolistic competition.

+ Smartphones
+ Toothpaste
+ The cereal aisle in the grocery store (if you ignore they are made by the same company)


## Assumptions

+ Many buyers and sellers
+ Heterogeneous goods.  There are non-price differences.
+ Firms have price setting behavior.
+ Free entry and exit
+ All firms effect all other firms.  Nothing is local.

The model is used a lot of macroeconomics but only at the EC312 and higher level.

## Good Things About Monopolistic Competition

+ Good at small innovation
+ More personalized, while still mass produced
+ Preserves historical variety

## Small Innovation

Technical Rain jackets

+ Napoleon  pockets
+ Pit zips
+ Low cut in back

American Hefeweizen

## More Personalized

+ Shoes and foot models
+ Cut of pants

## Preserve Historical Variety

+ Tomatoes
+ The Porter
+ Modelo Negra

## The Graphs are the same as Monopoly

## The Bad Things

+ Price and quantity effects
    + Price is higher
    + Less is sold
+ Welfare Effects
    + DWL
    + Reduction in CS

The long-run effects are a little different.


## What is Different? 


+ Entry and exit, yes but how they enter and exit.
+ Entry and exit means that profits are competed down to zero.


Try drawing a monopoly graph with zero economic profit.  


## MC in Long-Run


## Why and How Does That Happen?

Every time a firm leaves or enters, all the other firms' demand functions change.

+ Entry and exit cause decreases and increases in demand.
+ It also changes the elasticity depending on how similar.


## Lets Talk Beer

Imagine I own the only brewery in a small town.  People can either drink the one beer I make, a pilsner, here or they can sit at home and drink water (moist county).

+ If I increase the price of beer -- more people stay home.
+ If I decrease the price of beer -- more people come in

In other words it is a demand curve but pretty inelastic.

## A New Brewery Comes to Town

They make a stout.

Now people have three choices:

+ Drink pilsner here.
+ Drink stout there.
+ Drink water at home.

##  Pretend people have strong beer tastes

+ They either like pilsner or stout
+ Some are willing to switch sides because -- beer.


You lose some customers, decreasing demand.

## Decrease Demand

## What if ...

They make a pilsner too?

We make the same beer.  They are perfect substitutes.

+ If my price is higher -- no customers
+ If my price is lower -- all the customers

We are now perfect competitors and take price as given.  $P=AR=MR=D_{firm}$ Again

## What if ...

They made and IPA?

Similar to, but not the same, and people that like pilsners also like IPAs

Customers become more sensitive to price: 

+ If I raise price, some go home and drink water, others leave to drink IPA.
+ If I lower price, some water drinkers come back, and some IPA drinkers come back.

The more similar the new product, the more your demand curve rotates, becomes more elastic.

## How Entrant Changes Your Demand

## Now Pretend You are the Entrant

What kind of beer do you make?

+ Similar enough to steal customers
+ Not so similar so that you have market power

## Beerspace

## Each New Entrant

+ Picks a spot where there is profit.
+ Lowers everyone's profit
+ Sooner or later there are no more profitable spots -- everyone has zero economic profit.

This is an evolutionary equilibrium

## In the Long-Run

+ Profits are zero, same as PC.
+ Costs are higher than the minimum of average cost, different than PC.
+ The produce less than quantity at min of AC.  They have excess capacity
