---
title: "Syllabus and The Class"
output: beamer_presentation
theme: "Berlin"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Plan for the Day

+ Walk through the syllabus
+ Walk through tools and resources

## Syllabus

You can find the syllabus here. (https://github.com/woodsjam/Course-Intro-Microeconomics/blob/master/SyllabusEC201Woods.pdf)

Some slides will also be on github. (https://github.com/woodsjam/Course-Intro-Microeconomics)

+ Download them before each class if you like, but they are not a substitute for coming to class.


## Intro Micro (Official)

A study of the choices individuals face as participants in the markets for goods, services and factors of production like labor; behavior of profit-maximizing firms operating in markets with varying degrees of competitive pressure; potential role of government in intervening to influence market outcomes using taxes and subsidies; reasons for international trade and economic inequality.

## Intro Macro (Unofficial)

+ Talk many of you out of a business degree.
+ Convince you that economics is not **just** about money or markets
+ Make the news and politicians funnier.
+ Talk some of you into being econ majors.


"Every man should have a built-in automatic crap detector operating inside him. It also should have a manual drill and a crank handle in case the machine breaks down." -- Hemingway 


## Who Am I?

+ Ph.D. Economist, UC Davis
+ First generation college, like many of you.
+ Background in energy and program evaluation consulting going back to the early 90s.
    + Projects were multidisciplinary. Rarely did a project not involve, economists, engineers and others.
    + I have steel toed boots.
+ Former:
    + Oregon HECC commissioner
    + Parkrose School Board Chair
    + Multiple non-profit boards
    + County Budget Committees
    + Legislative Candidate.
+ Hobbies: Painfully Stereotypical Portlander

    
## Warnings

+ I'm Dyslexic.  If you see a slide without a typo -- be amazed.
+ Don't think that you have to understand everything
    + You should read everything.
    + I usually read things over and over again and learn new things every time.
    + If you understand half -- amazing.
    + The more you read, the easier it is to learn more.  It really builds on itself.
+ Don't be afraid to Google a picture or an article to help you understand something in class.
    + You need to learn how to help yourself.
    + Learned helplessness is a pet peeve of  mine.
+ Do not wait till the last minute  
    + Don't make an optimistic, tightly scheduled plans.
    + No plan survives contact with reality
    + Start everything as early as possible.


## Key Dates

+ Final Exam: March 19th,	8:00AM-09:50 
+ Midterm 1: January 30th
+ Midterm 2: February 25th
+ Last Day to Withdraw or Change Grade Option: February 24th.
+ Holiday: January 21st


Exams will be given on those days and at those times only.  I do not give make up, early or late exams. Get those on your calendars.  Make sure you are not scheduled to work or deciding to fly somewhere.

DRC People:  Schedule time slots in testing center so that you start at the same time as the rest of class.

## Contact Information

+ My office is in CH 241-O.
+ Drop in office hours are Monday 2:30-3:30  through the last week of class. There is no need to make an appointment for these hours -- just come.
+ If you can't attend regular office hours, please check my calendar https://woodsj.youcanbook.me/. I will make a limited number of 20 minute slots available each week. If you make an appointment and fail to show up without first canceling, I will penalize your final exam score two points. 

My in-person office hours may need to be moved to a different location because of construction in Cramer Hall.  

Meetings can be via phone or even the hangout/meet function in your pdx.edu email.

I will also keep Slack up during office hours to answer questions.

## Slack

I avoid email since it is a trash heap and a constant distraction.

+ The class will use slack https://psuwinter2019ec201.slack.com
+ Handles direct messages, forum style responses.
+ You should be able to sign up with your pdx.edu account
+ Can access via webpage, apps in Android and iOS.
+ Linked in d2l.
+ Officially supported PSU software
+ Common in industry
+ Many of you already use it.

## Hints on Slack

+ Prefer #general to direct messaging me.
    + Questions about course material is for #general
    + Questions about your grade or anything private is for @james woods
+ "I can't find it anywhere" is usually answered with:
    + A link to a google search.
+ Don't start and end with, "I got 7 but the key shows 245.  What did I do wrong?"
    + Show your work.  The fix is often a single parameter.
+ Provide full text of the question you are working on.

In short, make it easy for someone to help you.

## More Slack Hints

+ Rants and bellyaching put you at the bottom of the queue or off the queue.
+ Night before the exam?  You are on your own.
+ Set personal Do Not Disturb times.  It it defaults to 10pm -8am


## Textbook 

Krugman, Paul R., and Robin Wells. Microeconomics ed. 5., Worth Publishers, 2018.(ISBN-10: 1-319-09878-9).  

+ This textbook is amazingly overpriced.
+ Will not be assigning questions out of the book.
+ Hint: You can rent an earlier edition for  under $20 just make it line up with the 5th edition readings.

## Exams

+ Closed book, notes, internet, friend, etc.
+ Multiple choice but not, "what is the definition of .." style.
+ ID check
+ Bags, phones, smart watches at the side or front of room.
+ Many versions of the exam.
 
## In-class quizzes

+ Could be one each class
+ Check if you completed the reading
+ Check if you reviewed earlier classes.
+ Key provided via email to your @pdx.edu account.

Do yourself a favor and review these questions.


## Homework

+ At most weekly.
+ Turned in via D2L either as a D2L "quiz", or as a pdf or word document through D2L "assignment" function. 
+ Do not write the assignments out by hand and then turn in a photo in pdf form.

These tend to be harder questions that combine two or more ideas from lecture.  Don't expect to knock them out in 30min.  

## D2L

I will assume you know how  to work D2L. 

+ Calendar on left
+ Links in the middle
+ Content, Quizzes and Grades up top

## D2L Key Takeaways

+ Homework is either an "assignment" or a "quiz" depending on if the homework is written or multiple choice.
+ Both show in the calendar
+ Typically due Friday at noon.
+ At least a week notice

## Assessments and Grade Policy

+ Final Exam (30%)
+ Midterm 1 (20%)
+ Midterm 2 (20%)
+ In-class quizzes (20%)
+ Homework (10%)

## Grades Based on Class Rank

+ Course Grade Distribution: ~30% As, ~30% Bs, ~12% Cs
+ Based on class rank
    + Not 90% and above is an A...
    + Expect exams to use the full range.

Example: .84, .82, .77, .76, .75, .65, .64, .50, .44, .2, .1   


+ Grade breaks are in the gaps.
+ The median, i.e., middle, student will earn a B.

## From My Last EC202

https://github.com/woodsjam/Course-Intro-Microeconomics/blob/master/DayOne/MT2Analysis.pdf

In summary:

+ I use the full range of points.
+ Most people don't change their behavior.
+ Don't miss class.
+ Do your homework.

## What I learned in Fall from teaching EC202

+ I don't pay much attention to teaching evaluations.  They self-select the bottom of the class.
    + Mostly I found out that when students don't show up to class and miss key worked examples and concepts -- they blame me.
+ I do an end of term debrief with the class.
    + I implemented many ideas from my end of term debrief relating to course mechanics.
    + How the exam questions work.
    + The sticks and carrots of the class.

But, I am powerless in the face of your indifference.

## It is your effort, not mine

+ I can give you exercises that use the tools discussed in class -- but if you don't do them ...
+ I can give you feedback and answer keys -- but if you don't look at them.
+ I give guidance on what to read -- but if you don't read.

You paid a "small" dollar amount to take this class, but the biggest cost is your motivation, effort and time. 

## Over the Break

+ The school of business has been concerned with students not learning in EC201/202 and gave a knowledge test to their students.
    + Students missed anything mathematical -- even percent change.
    + Students only were able to answer Costa's Level 1 questions but little else.  For example, students could recognize a definition but could not an example that satisfies the definition.

Which is why we are taking a [15 minute pre-test](https://e.ggtimer.com/10%20minutes)

## Econ Break

We will look at these in greater detail later.

+ Principle #1: Choices are necessary because resources are scarce. 
+ Principle #2: The true cost of something is its opportunity cost. 
+ Principle #3: How much is a decision at the margin. 
+ Principle #4: People usually respond to incentives, exploiting opportunities to make themselves better off. 

Why did I allocate grades the way I did?

## Why from My POV?

+ Principle #1: Choices are necessary because resources are scarce. 
    + Had to add up to 100%
    + Only so much time I can grade.
+ Principle #2: The true cost of something is its opportunity cost. 
    + Focus on higher quality, in-class, information.
    + Making sure I am giving **you** the grade and not someone else.
+ Principle #3: How much is a decision at the margin. 
    + More on homework would mean less on exams or quizzes.
    + Balanced to achieve my objective -- you knowing things and being able to do things.
+ Principle #4: People usually respond to incentives, exploiting opportunities to make themselves better off. 
    + I am manipulating you.
    + What am I trying to get you to do?

## Show up

Duh!

## Do your Own Work

+ A few facts on scale. https://www.plagiarism.org/article/plagiarism-facts-and-stats

+ How easy is it to outsource your class? https://www.google.com/search?q=take+my+online+class+for+me&rlz=1C1GGRV_enUS751US753&oq=take+my+online+class+for+me&aqs=chrome..69i57.4986j0j4&sourceid=chrome&ie=UTF-8

## Stop Procrastinating

+ Plenty of studies show that at least 2/3rds of you procrastinate.
+ Regular interaction, to create habit, is supposed to help.

http://success.oregonstate.edu/learning/stop-procrastinating

## What am I trying to get you to do?

+ Come to class.
+ Do your own work.
+ Work with the material regularly -- several times a week -- so you don't procrastinate.

## Bonus Question

Principle #2: The true cost of something is its opportunity cost.

+ Final Exam (30%)
+ Midterm 1 (20%)
+ Midterm 2 (20%)
+ In-class quizzes (20%)
+ Homework (10%)

So ...

+ What is most important?
+ Do the 'points' fully describe the opportunity cost?

## Looks like the Final but it isn't

+ What is the opportunity cost of not coming to class?
    + Can't take the quiz
    + You only get the slide version of the lecture, not the full version.
    + Do you think you can do well on the homework and exams without attending class?
  
  
The most expensive part of a meal is not always the best part. Price, the financial part, does not always indicate quality or importance.

## So about you business majors

"With a five-year 31% underemployment rate according to Burning Glass, and a massive 601,092 degrees passed out in 2016, business and related majors produced a staggering 186,339 people with a degree and no corresponding college-level job. Counting the initial underemployment rate for business and related majors of 47%, a whopping 282,513 were underemployed in 2016." 

-- Strada Institute for the  Future of Work




## What are your local economists working on?

+ Randy Bluffstone: Ethiopia and Nepal stoves.
+ Sahan Dissanayake: How to preserve forests and farmland
+ John Gallup: Estimating income inequality when data is not great
+ John Hall: Heterodox
+ Hiro Ito: Trade imbalances and key currencies, and resiliency after natural disasters.

## More local economists

+ Arnab Mitra:  Lab experiments on dishonesty.
+ Cesar Rodriguez: Effects of financial openness on exchange rates
+ Rajiv Sharma: Did Obama-care increase discrimination
+ Sarah Tinkler: Rajiv and her are coauthors on many papers.

## More

+ Forrest Williams: How you get people to donate more
+ ME: How do you get more energy efficiency and what else do you get with it.
+ Grade Arnold: Applied microeconomist. Last seminar was on if female CEOs were penalized more than male.
+ Riju Joshi: The econometrician!  


##  

How to Study: Hints from a successful student

## Class Notes

+ If you only write down what I write or what is on the slides -- you are not taking notes.
+ The things I say are important too
    + If it wasn't, why come to class?
    + I could post the slides
    + Better, put them up and set a 1 min slide advance

## What Should be in Your Class Notes

+ The usual, facts, diagrams, definitions, quotes

+ Questions as they occur to you. 
    + My notes have a lot of questions
    + Cross them off as they get answered
    + If one lingers too long -- ask.
+ Criticism
    + If something doesn't sound right, note it.
    + All models are limited and can handle everything.
+ Emotional reaction
    + My notes have a lot of swearing in them.
    + It's like Morse code

## Class Notes are Not Course Notes

+ Use the notes you take in class to build notes for the course
+ I often took notes on the paper towels from the bathroom.
+ Notes should be recopied and reorganized before you go to bed, or at least when you get up the next morning.

They should include:

+ Clarifications from the text
+ Worked examples
+ Organized how you think of them.  It could be different than mine.
+ Highlights of key concepts, equations, figure
+ References to earlier notes

## Course Notes

I can, and do still do, read mine more than 25 years latter.

Can your read yours from last term?

Hint: Everyone in my graduate cohort created course notes from class notes. 

+ Those are, by definition, very successful students
+ Was done even when the weekly homework for a single class takes 20 hrs.
+ You always have time to save time.

## Course Notes are Not Study Notes

+ Don't study by turning pages.
+ Start early.
    + The weekend before the exam is not early, that is late
    + Review for exam is continuous.
+ Study notes contain:
    + What you don't understand yet
    + What you definitely need to know
+ You revise them down as you learn things
    + My goal was always to get them down to one side of a note card the day of the exam.
    + One good exam I had, "Nachos", on the card.  Nothing  to do with the class but I was well prepared.

## Come to Office Hours

Early 90s I had two classes of 20

+ At *least* 30 would come to each office hour.
+ Two hours a week, Ten weeks
+ 30 * 2 * 10 = 600 student contacts

NOW

+ Two or three students two or three times
+ 10 student contacts

##  Observation 

+ I give pre-tests in my other courses to see how much students remember about prerequisites.
+ Younger student that took prerequisites a year ago, remember almost nothing.
+ Older students that took prerequisites more than 30 years ago, remember a lot more.


## Get a Group

Clarification: Get a *good* group

How to tell that you have a good group:

+ Everyone is sure they are the idiot of the group.
+ They call you out when you are not doing your work
+ Someone can explain everything, but it isn't the same someone every time.
+ Those pose course  questions that you didn't think of -- and can explain the answers.
+ When you fall, and you will, the group will pick you up.

## Group Hints

+ This is the 21st century, you don't have to gather in the library.
+ If people can study together for the Master Sommelier exam through Skype, you can study econ.
+ If someone is not pulling their weight -- ditch them.
+ Groups are for mutual benefit.

## Study Every Day

You have a marathon in March.  How do you train?

+ Run for 60 hrs straight in the four days before
+ Run every day, with break days, building up to a good performance.

Just schedule an hour a day for this class.  Make it a habit.

## Learn How to Read

It is a multipass system.

+ Read the Title and abstract (Papers)
+ Read the section headings
+ Read the introduction
+ Read the conclusion
+ Look at the figures
+ Look at the equations
+ Skim the whole thing
+ Read it but don't freak out if you don't get everything.
    + Keep notes on your reactions, how the topic connects back and questions 
    + Repeat as time allows.

You, and the author, will never fully understand the paper/chapter.

## The Summary of Hints

+ Class notes should be way more than  what is on the board or slides.
+ Class notes are not course notes.
+ Make course notes THAT day.
+ Make study notes from course notes.  
+ Study notes get shorter the closer you get to the exam.
+ EVERY DAY and don't skip leg day.
+ Come to office hours, but come with purpose.  Don't show up and say you came because I told you.
+ Get a *good* group
+ Learn to multipass read and read a lot.