---
title: "How to Study: Hints From a Successful Student"
theme: Berlin
output:
  beamer_presentation: default
  theme: "Berkeley"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Preliminaries

+ Convince yourself that you can learn.  
+ Learning is by definition done by you.  Nobody can do it for you, just like nobody can eat your dinner for you, or do your exercises for you.  
+ I teach, meaning help, give feedback, curate topics, and pose problems, but the learning is your effort.  Teaching is a bit like pushing on a string.  I can do my thing, but if the student does not do theirs, there is no learning.  
+ Phrases like, "I'm online this term which means I'm teaching myself X", misunderstands the roles and your part.


##

+ Convince yourself that learning is easy.
+ Learning is easier the more you know.  
  + It is the Ph.D.'s secret.  
  + We are very good at the skills needed to learn, we think it is easy, and we know so much that new things, in our area, are fast and easy to learn.
+ It is often hard to unlearn something that is not true.
  
## Topics

+ Class notes
+ Relationship between class notes and course notes.
+ Relationship between course notes and study notes.
+ Ask faculty for help
+ Get a group
+ Study every day
+ Learn to read -- academic skim.

## Class Notes

+ If you only write down what I write or what is on the slides -- you are not taking notes.
+ The things I say are important too
    + If it wasn't, why come to class?
    + I could post the slides
    + Better, put them up and set a 1 min slide advance
+ The things you think are important too    

## What Should be in Your Class Notes

+ The usual, facts, diagrams, definitions, quotes

+ Questions as they occur to you. 
    + My notes have a lot of questions
    + Cross them off as they get answered
    + If one lingers too long -- ask.
+ Criticism
    + If something doesn't sound right, note it.
    + All models are limited and can't handle everything.
+ Emotional reaction
    + My notes have a lot of swearing in them.
    + It's like Morse code

## Strange But True

+ Volume of notes matters.  
+ The pen is greater than the keyboard.
+ You have to review the notes if they are going to help.


## Class Notes are Not Course Notes

+ Use the notes you take in class to build notes for the course
+ I often took notes on the paper towels from the bathroom.
+ Notes should be recopied and reorganized before you go to bed, or at least when you get up the next morning.

They should include:

+ Clarifications from the text
+ Worked examples
+ Organized how you think of them.  It could be different than mine.
+ Highlights of key concepts, equations, figures
+ References to earlier notes

## Course Notes

I can, and do still do, read mine more than 25 years latter.

Can your read yours from last term?

Hint: Everyone in my graduate cohort created course notes from class notes. 

+ Those are, by definition, very successful students
+ Was done even when the weekly homework for a single class takes 20 hrs.
+ You always have time to save time.

## Course Notes are Not Study Notes

+ Don't study by turning pages.
+ Start early.
    + The weekend before the exam is not early, that is late
    + Review is a continuous process.
+ Study notes contain:
    + What you don't understand yet
    + What you definitely need to know
+ You revise them down as you learn things
    + My goal was always to get them down to one side of a note card the day of the exam.
    + One good exam I had, "Nachos", on the card.  Nothing  to do with the class, but I was well prepared.

## Come to Office Hours

Early 90s I had two classes of 20

+ At *least* 30 would come to each office hour.
+ Two hours a week, Ten weeks
+ 30 * 2 * 10 = 600 student contacts

NOW

+ Two or three students two or three times
+ 10 student contacts

##  Observation 

+ I give pre-tests in my other courses to see how much students remember about prerequisites.
+ Younger student that took prerequisites a year ago, remember almost nothing.
+ Older students that took prerequisites more than 30 years ago, remember a lot more.

... So I tied an onion to my belt, which was the style at the time

## Get a Group

Clarification: Get a *good* group

How to tell that you have a good group:

+ Everyone is sure they are the idiot of the group.
+ They call you out when you are not doing your work
+ Someone can explain everything, but it isn't the same someone every time.
+ Those pose course  questions that you didn't think of -- and can explain the answers.
+ When you fall, and you will, the group will pick you up.

## Group Hints

+ This is the 21st century, you don't have to gather in the library.
+ If people can study together for the Master Sommelier exam through Skype, you can study econ.
+ If someone is not pulling their weight -- ditch them.
+ Groups are for mutual benefit.

## Study Every Day

You have a marathon in March.  How do you train?

+ Run for 60 hrs straight in the four days before
+ Run every day, with break days, building up to a good performance.

Just schedule an hour a day for this class.  Make it a habit.

## Learn How to Read

It is a multipass system typically called academic skimming

+ Read the Title and abstract (Papers)
+ Read the section headings
+ Read the introduction
+ Read the conclusion
+ Look at the figures
+ Look at the equations
+ Skim the whole thing
+ Read it but don't freak out if you don't get everything.
    + Keep notes on your reactions, how the topic connects back and questions 
    + Repeat as time allows.

You, and the author, will never fully understand the paper/chapter.

## The Summary of Hints

+ Class notes should be way more than  what is on the board or slides.
+ High volume with a pen, not a keyboard.
+ Class notes are not course notes.
+ Make course notes THAT day.
+ Make study notes from course notes.  
+ Study notes get shorter the closer you get to the exam/end of course.
+ EVERY DAY and don't skip leg day.
+ Come to office hours, but come with purpose.  Don't show up and say you came because I told you.
+ Get a *good* group
+ Learn to multipass read and read a lot.