---
title: "Worked Production and Cost"
output: beamer_presentation
theme: "Berlin"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Half Week?

+ Why we have only one module this week.  There will be two next week.
+ The next modules on perfect competition trough monopoly are the hard ones in the class.
+ We are currently about two weeks behind the usual for in-person courses.

# Exercise 1 (Groups)

Give three examples, with context, of:
+ Fixed input/cost
+ Variable input/cost

Give the reason why you think the input/cost is variable or fixed.

Nominate a speaker.

# A few Rules on costs

+ FC is fixed
+ $TC = VC + FC$
+ $VC(0) = 0$
+ $AC = AVC + AC = \frac{TC}{Q} = \frac{VC}{Q} + \frac{FC}{Q}$
+ $MC(Q) = TC(Q+1) - TC(Q) = VC(Q+1) - VC(Q)$ The non-calc definition varies by textbook.  Caution.

# Exercise 2 (Whole Class)

Fill in the blank and say why.

Q    | TC      | VC    | FC   | AC   | AFC   | AVC | MC  |
---  |---      |---    |---   |---   |---    |---  |---  |
0    |  2      |       |      |      |       |     |  3  |
1    |  5      |       |      |      |       |     |     |
3    |  12     |       |      |      |       |     |     |


# Exercise 3 (Groups)

Q    | TC      | VC    | FC   | AC   | AFC   | AVC | MC  |
---  |---      |---    |---   |---   |---    |---  |---  |
0    |         |       |      |      |       |     |    |
1    |         |  2     |  5   |      |       |    |     |
**4**|  20     |       |      |      |       |     |  x  |


# About the diagrams

You tend to see two kinds in the book:

1.  Linear Marginal Cost ($MC = \alpha q$): 
  + $AVC = \frac{\alpha}{2} q$
  + Profit maximizing is just where lines cross.
1. Parabolic Average variable cost ($AVC  = \alpha (q - m)^2 + b$)
  + Shows the increasing marginal product of labor, declining marginal cost range.
  + Infinities for low q.
  
# Getting Diagrams Right is Key   

You need to be able to see the relationships.

+ The steps and graphical hints are mostly to help you see the basic relationships.
+ There are a few mathematical requirements, e.g., MC cuts AC at the min of AC, but otherwise the hints are to give you enough space to see areas.
+ The order is different depending if you are drawing linear marginal cost or parabolic AVC.


# Steps: Linear Marginal

+ Axis with labels.  $ or costs list, AC, MC, etc and q/t is fine.
+ Draw in MC as a line with zero intercept
+ AVC line half as steep as MC with intercept at zero.
+ AC is hard:
  + AC = AFC + AVC
  + Starts far above AVC since AFC is large for small q.
  + Gets closer to AVC as q increases
  + Is cut by MC at the minimum.
  + Looks like a skewed parabola
  
# Try it.  Four people at a time in groups.


# Steps: Parabolic AVC

+ Axis with labels.  $ or costs list, AC, MC, etc and q/t is fine.
+ Draw AC as a smile that covers about 2/3 of your graph. 
+ MC looks like a fish hook or Nike Swoosh that cuts AC at the minimum.
+ AVC is hard:
  + AC = AFC + AVC
  + Starts far below AC since AFC is large for small q.
  + Gets closer to AC as q increases
  + Is cut by MC at the minimum.
  + Looks like a skewed parabola

# Try it.  Four people at a time in groups

#  So now what?

At this level, economics has a specific modus operandi 

+ Figure out what the actor wants, the objective function.
+ Figure out the constraints, costs, income, ...
+ Maximize (or minimize) the objective function subject to those constraints.

We will assume that the goal of the firm is profits, $\Pi$, which we define as revenue less costs.

# Warning

+ Costs are more expansive to an economist.
    + We include opportunity cost.
    + Imputed salary of owner that takes no salary.
    + Impute rent when firm owns property, even things like desks
+ Because Costs are Different -- Profits are different.
    + Net Income, profit to an accountant, is always more than economic profit.
    + We include costs they don't
    
# Implication

$$Accounting~Profit - Opportunity~Costs = Economic~Profit$$

Just because you have positive accounting profits, net income, does not mean you have positive economic profits

# Profit

$$\Pi = Rev(q) - Cost(q)$$

+ Positive profit 
    + Greater than can be achieved elsewhere in the economy for the same risk.
    + Expect net entry soon
+ Zero or Normal Profit
    + Equal to what can be achieved elsewhere for the same risk.
    + No net entry or exit
+ Negative: Less
    + Net exit

Note that risk is built in.  The higher the risk the more profit needed.


# Example

+ A very safe 2% return may be positive economic profits.
+ A very risky 15% return may be negative economic profits.


# So what Does the Firm do?

Competitive firms observe a price and choose output to maximize profit.

+ They can't control price and can only react.
+ Profit, not maximum per unit.
+ Calc people will see this as an optimization problem.

# Forget this formula

$$\max_q R(q) - C(q)$$

# Profit Max Q with Marginal Revenue and Marginal Costs

# Steps

+ Find $q^*$ where $MC = MR$
+ Start at $q^*$ go to AC and hang a left.  
    + That is $AC^*$.
    + Box is Total Cost, $TC^* = AC^* q^*$
+ Start at Start at $q^*$ go to $AR=P=MR=D_{firm}$ and hang a left.  
    + That is $AR^*$.
    + Box is Total Revenue, $TR^* = AR^* q^*$
+ Little box on top is profit.

# Positive Economic Profits (AR > Min AC)
Weird sunglasses shows up when there is positive economic profits.


# Negative Economic Profits (AR < Min AC)

# Negative Profits

+ No Weird sunglasses thing but a funny triangle.
+ Does not mean you go out of business or exit.
    + But you could make more in another industry.
+ There is a shut-down condition
    + If AVC > AR, shut down
    + Not out of business.
+ Why all stores are not 24/7.
    + The revenue from staying open (AR) is less than the costs of lights and labor (AVC).
    + Exit and Entry is a long term topic which we handle elsewhere.
    
# Why Shutdown?

$$\Pi = TR - FC - VC$$
When TR<VC you are better off just paying FC and let $TR=0$ and $VC=0$.

$$\Pi = (TR - VC) - FC < -FC$$


# Long-Run

Long-run, long enough for all inputs to be variable or long enough for entry and exit to take place.

Two approaches:

+ Individual firms changing size, the _intensive margin_, which involves long-run average cost, is done in EC 311/415 at PSU. 
+ Firms entering and exiting, the _extensive margin_, is what we will do here.


#  How Long is Long-Run

Long-Run : Long enough for all inputs to be variable or long enough for entry and exit to take place.

+ Could be a week  -- think how fast you can move a food cart from one pod to another.
+ Could be 10 years -- The aluminum industry saw no entry for 10 years in the lead up to WWII.

There is never a specific  time, but if a firm can enter and exit faster and change scale faster -- they have an advantage (OODA Loop argument)


# Long-Run Equilibrium Defined

+ The market is in short-run equilibrium.  Supply = Demand.
+ Firms earn zero economic profit.


Off to breakout rooms to make cost curves where the firm earns zero economic profit.

# Hints

Price should be equal to the minimum of average cost


+ Find $q^*$ where $MC = MR$
+ Start at $q^*$ go to AC and hang a left.  
    + That is $AC^*$.
    + Box is Total Cost, $TC^* = AC^* q^*$
+ Start at Start at $q^*$ go to $AR=P=MR=D_{firm}$ and hang a left.  
    + That is $AR^*$.
    + Box is Total Revenue, $TR^* = AR^* q^*$
+ Little box on top is profit. (But has zero area)


# Long-Run Equilibrium Graphically

#  Increase the demand for the good

+ Demand increases and therefore price and market transactions increase.
+ As price increases the individual firms:
    + Increase output
    + Increase profits
+ Then in the long-run
    + Positive profits induce entry.
    + Entry causes an increase in supply (Increase in # of firms)
    + That reduces price and increases market transactions
    
    
# And Then

+ Individual firms then
    + Decrease output as the price falls
    + See decreased profit.
+ Until a New Long-run equilibrium is established
    + Supply = Demand
    + Profits are zero


# Graphically    


# Summary of price and quantity changes

+ Markets:
    + SR: Price increase and transactions increase.
    + LR: Supply increases which causes prices to fall and market transactions to increase.
+ Individual Firms:
    + SR: Production and profits increase.
    + LR: Both production and profits decrease to original
    
In the end, there are more firms to serve the increased demand.    

# Now Lets Change the Rental Rate

This is the story of how food carts developed in Portland as a result of the 2008 recession and some changes in Portland law that allowed food carts to exist.

+ Brick and Mortar restaurants are expensive with high rents but there is no alternative.
+ City changes rules around restaurants allowing more food carts
+ A new cheaper alternative to paying brick and mortar rents.

Think of this as what happens to restaurants when the building rents decrease.

# Problem 1

+ Figure out which cost curves move and it what direction when the rental rate, r, the price of the fixed input decreases.
+ Work with a table like this and cut FC in half


Q    | TC      | VC    | FC   | AC   | AFC   | AVC | MC  |
---  |---      |---    |---   |---   |---    |---  |---  |
0    |    2    | 0      |2      |      |       |     |  1  |
1    |    2    |  1     | 2     |      |       |     |   3  |
3    |  6     |   4    |  2    |      |       |     |     |

        
# What did you see?

+ FC decreased
+ TC decreased
+ AC decreased
+ AVC unchanged
+ MC unchanged


# Finish Long-Run

AC decreased

+ What happens to profit?
+ Does this lead to entry or exit?

# Summary

+ The AC function shifts down
+ Individual Firms:
    + Don't change output, MC did not change.
    + Profits increase/become positive

# Continue into the long-run

+ What happens to supply because of entry?
+ And therefore what happens to price and quantity in the market?
+ As the price changes, what happens to $q*$ and $\Pi$ for individual firms?

# Summary


+ Positive profits induce entry.
+ Entry causes an increase in supply (Increase in # of firms)
+ That decreases price and increases market transactions

# Graphically
    
# What About Individual Firms?

In the long-run do they:

+ Produce more or less than before?
+ What are their costs and profits?

# Summary

+ Individual firms then
    + Decrease output as the price decreases
    + Profits fall towards zero.
+ Until a New Long-run equilibrium is established
    + Supply = Demand
    + Profits are zero

# Graphically    


# Summary of price and quantity changes

+ Individual Firms:
    + SR: Production unchanged but profits increase.
+ Markets:
    + LR: Profit increase causes firms to enter. Supply increase which causes prices to fall and market transactions to increase.
+ Individual Firms:
    + Prices fall until profit is again zero.
    + As the prices falls, individual firms decrease output.
    
In the end, there are more food carts that serve fewer customers individually, but more collectively.  
